image: ddgg/php_2021:build_v1

pipelines:
  default:
    - step:
        caches:
          - composer
        services:
          - mysql
        script:
          - while ! timeout 1 bash -c "echo > /dev/tcp/localhost/3306"; do echo "Waiting for MySQL..."; sleep 1; done
          - pushd project/
          -   composer install
          -   cp .env.example .env
          -   php artisan key:generate
          -   php artisan migrate:fresh
          -   php artisan db:seed
          -   mysqldump -h127.0.0.1 -u root --password=root123 test > tests_codeception/_data/dump.sql
          -   vendor/bin/phpunit --log-junit tests/_output/test_report.xml
          -   php artisan serve --port 8888 &
          -   while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8888"; do echo "Waiting for server..."; sleep 1; done
          -   vendor/bin/codecept run --xml test_report.xml
          -   killall php php8.0
          - popd
          - .ci/collect_reports.sh
definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test123
